CoTFBWebRole/Controllers/AdminManagerController.cs
using CoTFBWebRole.Models;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace CoTFBWebRole.Controllers
{
    public class AdminManagerController : Controller
    {
        private CoTfbDbContext db = new CoTfbDbContext();

        protected override void Dispose(bool disposing)
        {
            if (db != null)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        [Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            var model = db.Users.Select(u => new UserViewModel
            {
                UserId = u.Id, 
                FirstName = u.FirstName,
                Username = u.UserName,
                City = u.City,
                Country = u.Country
            }).ToList();
           
            return View(model);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Edit(string id)
        {
            EditUserViewModel model = null;
            using (var context = CoTfbDbContext.Create())
            {
                model = db.Users.Where(u => u.Id.Equals(id)).Select(o => new EditUserViewModel
                {
                    Username = o.UserName,
                    FirstName = o.FirstName,
                    City = o.City,
                    Country = o.Country,
                    Id = o.Id
                }).First();
            }
            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(EditUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                using (var context = CoTfbDbContext.Create())
                {
                    var user = context.Users.Where(u => u.Id.Equals(model.Id)).First();
                    model.MapToEntity(user);
                    context.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            return View();

        }

        [Authorize(Roles="Admin")] 
        public ActionResult Delete(string id)
        {
            if(id == null) { return new HttpStatusCodeResult(HttpStatusCode.BadRequest); }
            var user = db.Users.Find(id); 
            if(user == null) { HttpNotFound(); }
            return View();
        }

        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(string id)
        {
            var user = db.Users.Find(id);
            db.Users.Remove(user);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

CoTFBWebRole/Controllers/UserManagerController.cs
using CoTFBWebRole.Models;
using Microsoft.AspNet.Identity;
using System.Linq;
using System.Web.Mvc;

namespace CoTFBWebRole.Controllers
{
    public class UserManagerController : Controller
    {

        private CoTfbDbContext db = new CoTfbDbContext();
        protected override void Dispose(bool disposing)
        {
            if (db != null)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        [Authorize(Roles = "User")]
        public ActionResult UserProfile(string id )
        {
            id = User.Identity.GetUserId(); 
            UserAccountViewModel model = null;
            using (var context = CoTfbDbContext.Create())
            {
                model = db.Users.Where(u => u.Id.Equals(id)).Select(o => new UserAccountViewModel
                {
                    Username = o.UserName,
                    FirstName = o.FirstName,
                    City = o.City,
                    Country = o.Country,
                    PictureUri = o.PictureUri,
                    Id = o.Id                  
                }).First();
            }
           
            return View(model);
        }

        public ActionResult Instruction()
        {
            return View();
        }

        public ActionResult Game()
        {
            return View();
        }

    }
}

CoTFBWebRole/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Curse Of the Fluffy Bunny", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (User.IsInRole("Admin"))
                    {
                        <li>@Html.ActionLink("List of Users", "Index", "AdminManager")</li>

                    }
                    @if (User.IsInRole("User"))
                    {
                        <li>@Html.ActionLink("Profile", "UserProfile", "UserManager")</li>
                    }
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Instruction", "Instruction", "UserManager")</li>
                        <li>@Html.ActionLink("Game", "Game", "UserManager")</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My Fluffy Bunny Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>